version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4002:4002"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    


