import dotenv from"dotenv";

const JWT_USER_PASSWORD=process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD=process.env.JWT_ADMIN_PASSWORD;
const STRIPE_SECRET_KEY="sk_test_51ROadeGD1XsyarQF43kfnWH0aPnrDK9cHI952uiQXgS3zdsHEOhCURjvXKNhGz2m0J6TVRDtjgseRCWQAU1HFlgN003QJsffS5"
export default{
    JWT_USER_PASSWORD,
    JWT_ADMIN_PASSWORD,
    STRIPE_SECRET_KEY
};